name: Condition Demo

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'prod'

    steps:
      - run: echo "Deploying to Production"